### ISSUE TITLE
image sizing issue

### ISSUE THREAD

**Issue by suryaumapathy2812** [aymaneMx/aymaneMx.com#27]
![Screenshot (2)](https://user-images.githubusercontent.com/32648210/146118349-8addcb80-9814-46f0-94d4-107f138a2c5b.png)
Checkout [here](https://surya-umapathy.netlify.app/posts)

**Comment by aymaneMx** [comment]
@suryaumapathy2812 Thank you for reporting this issue, I'll fix it as soon as I have free time.
also, contributions are welcomed, so feel free to create a PR 🙏

**Comment by aymaneMx** [comment]
https://github.com/aymaneMx/nuxt-portfolio-dev/pull/21 closed here
